package utils;

public enum DataType {
    INTEGER,BOOLEAN,TINYINT,SMALLINT,BIGINT,IDENTITY,DECIMAL,DOUBLE,REAL,TIME,DATE,TIMESTAMP,BINARY,OTHER,VARCHAR,VARCHAR_IGNORECASE,CHAR,BLOB,CLOB,UUID,ARRAY,ENUM,GEOMETRY,JSON,INTERVAL
}
